#ifndef CRYPTO_DILITHIUM_H
# define CRYPTO_DILITHIUM_H 1

# define DILITHIUM2_PUBLICKEY_BYTES  1312
# define DILITHIUM2_PRIVATEKEY_BYTES 2560

# define DILITHIUM3_PUBLICKEY_BYTES  1952
# define DILITHIUM3_PRIVATEKEY_BYTES 4032

# define DILITHIUM5_PUBLICKEY_BYTES  2592
# define DILITHIUM5_PRIVATEKEY_BYTES 4896

#endif /* !CRYPTO_DILITHIUM_H */
