FILESDIR = /usr/share/mk
FILES = stpd.base.mk stpd.clean.mk stpd.files.mk stpd.hostlib.mk
FILES += stpd.hostprog.mk stpd.inc.mk stpd.kernel.mk stpd.lib.mk
FILES += stpd.man.mk stpd.module.mk stpd.subdirs.mk

include stpd.files.mk
