name: Code Analysis

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install shellcheck cppcheck
        
      - name: Run shellcheck
        run: |
          shellcheck ./releasetools/cdimage.sh ./releasetools/floppyimage.sh ./releasetools/hdimage.sh  ./releasetools/image.defaults  ./releasetools/image.functions ./tools/version.sh

      - name: Run CppCheck
        run: |
          cppcheck -x c --std=c89 --quiet --error-exitcode=2 include sbin bin 
