name: Code Analysis

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install shellcheck cppcheck
        
      - name: Run shellcheck
        run: |
          shellcheck ./build.sh ./releasetools/cdimage.sh ./releasetools/floppyimage.sh ./releasetools/hdimages.sh  ./releasetools/image.defaults  ./releasetools/images.functions

      - name: Run CppCheck
        run: |
          cppcheck -x c --std=c89 --quiet --error-exitcode=2 include sbin bin 
